Option to use Pre-Prod certs for IKS use case
IBM/vpc-file-storage-mount-helper pull request #10
Opened 2024-03-28 06:35 UTC by saicharansunkara-ibm

These changes enable IKS team to install Pre-prod certs using input parameters in install.sh script.

If install.sh is ran with an input parameter of "stage", the pre-prod certs will be installed along with the Prod certs.

2024-03-29 04:34 UTC, prankulmahajan approved these changes
lgtm

2024-04-01 13:16 UTC, prankulmahajan commented
From IKS pipeline verified these changes. In case of stage cluster, the install.sh is able to take "stage" input and copy both pre-prod/prod certificates
```
It is a 'stage' cluster
This is a Debian-based system
No (mount.ibmshare) package currently installed on the system
Installing latest version available...
Linux(Ubuntu) Version(20.04) distro
Linux version supported - Ubuntu (20.04)
Using install app: apt-get
Wait for cloud-init to complete.

status: done
extended_status: degraded done
boot_status_code: enabled-by-generator
last_update: Mon, 25 Mar 2024 20:32:13 +0000
detail:
DataSourceNoCloud [seed=/dev/vdb][dsmode=net]
errors: []
recoverable_errors:
WARNING:
	- skipping /var/lib/cloud/instance/scripts/vendor as its not executable or the underlying file system is mounted without executable permissions.
Python 3.8.10 installed
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Package 'needrestart' is not installed, so not removed
0 upgraded, 0 newly installed, 0 to remove and 15 not upgraded.
Get:1 http://mirrors.adn.networklayer.com/ubuntu focal InRelease [265 kB]
Get:2 http://mirrors.adn.networklayer.com/ubuntu focal-updates InRelease [114 kB]
Get:3 http://mirrors.adn.networklayer.com/ubuntu focal-backports InRelease [108 kB]
Get:4 http://mirrors.adn.networklayer.com/ubuntu focal-security InRelease [114 kB]
Fetched 601 kB in 1s (487 kB/s)  
Reading package lists... Done
Package(strongswan-swanctl) - Available Version(5.8.2) - Min Version(5.4)
Installing package strongswan-swanctl
Reading package lists... Done
Building dependency tree       
Reading state information... Done
strongswan-swanctl is already the newest version (5.8.2-1ubuntu3.6).
0 upgraded, 0 newly installed, 0 to remove and 15 not upgraded.
Installing package charon-systemd
Reading package lists... Done
Building dependency tree       
Reading state information... Done
charon-systemd is already the newest version (5.8.2-1ubuntu3.6).
0 upgraded, 0 newly installed, 0 to remove and 15 not upgraded.
Installing package nfs-common
Reading package lists... Done
Building dependency tree       
Reading state information... Done
The following additional packages will be installed:
  libnfsidmap2 libtirpc-common libtirpc3 rpcbind
Suggested packages:
  watchdog
The following NEW packages will be installed:
  libnfsidmap2 libtirpc-common libtirpc3 nfs-common rpcbind
0 upgraded, 5 newly installed, 0 to remove and 15 not upgraded.
Need to get 0 B/361 kB of archives.
After this operation, 1365 kB of additional disk space will be used.
Selecting previously unselected package libtirpc-common.
(Reading database ... 70680 files and directories currently installed.)
Preparing to unpack .../libtirpc-common_1.2.5-1ubuntu0.1_all.deb ...
Unpacking libtirpc-common (1.2.5-1ubuntu0.1) ...
Selecting previously unselected package libtirpc3:amd64.
Preparing to unpack .../libtirpc3_1.2.5-1ubuntu0.1_amd64.deb ...
Unpacking libtirpc3:amd64 (1.2.5-1ubuntu0.1) ...
Selecting previously unselected package rpcbind.
Preparing to unpack .../rpcbind_1.2.5-8_amd64.deb ...
Unpacking rpcbind (1.2.5-8) ...
Selecting previously unselected package libnfsidmap2:amd64.
Preparing to unpack .../libnfsidmap2_0.25-5.1ubuntu1_amd64.deb ...
Unpacking libnfsidmap2:amd64 (0.25-5.1ubuntu1) ...
Selecting previously unselected package nfs-common.
Preparing to unpack .../nfs-common_1%3a1.3.4-2.5ubuntu3.6_amd64.deb ...
Unpacking nfs-common (1:1.3.4-2.5ubuntu3.6) ...
Setting up libtirpc-common (1.2.5-1ubuntu0.1) ...
Setting up libnfsidmap2:amd64 (0.25-5.1ubuntu1) ...
Setting up libtirpc3:amd64 (1.2.5-1ubuntu0.1) ...
Setting up rpcbind (1.2.5-8) ...
Created symlink /etc/systemd/system/multi-user.target.wants/rpcbind.service → /lib/systemd/system/rpcbind.service.
Created symlink /etc/systemd/system/sockets.target.wants/rpcbind.socket → /lib/systemd/system/rpcbind.socket.
Setting up nfs-common (1:1.3.4-2.5ubuntu3.6) ...

Creating config file /etc/idmapd.conf with new version
Created symlink /etc/systemd/system/multi-user.target.wants/nfs-client.target → /lib/systemd/system/nfs-client.target.
Created symlink /etc/systemd/system/remote-fs.target.wants/nfs-client.target → /lib/systemd/system/nfs-client.target.
nfs-utils.service is a disabled or a static unit, not starting it.
Processing triggers for systemd (245.4-4ubuntu3.23) ...
Processing triggers for man-db (2.9.1-1) ...
Processing triggers for libc-bin (2.31-0ubuntu9.14) ...
Selecting previously unselected package mount.ibmshare-0.0.3.
(Reading database ... 70793 files and directories currently installed.)
Preparing to unpack mount.ibmshare-0.0.3.deb ...
Unpacking mount.ibmshare-0.0.3 (0.0.3) ...
Setting up mount.ibmshare-0.0.3 (0.0.3) ...
Installing certs for stage environment...
Info  - IpSec using StrongSwan(5.8.2)
Debug - Folder created:/opt/ibm/mount-ibmshare/certs
Debug - RunCmd: ListNfsMounts (mount -t nfs,nfs4)
Debug - Existing nfs/nfs4 mounts found:0
Debug - StrongSwan cleanup config files Total(0) Mounted(0) Deleted(0) Recent(0)
Debug - RunCmd: /usr/sbin/swanctl --list-conns
Debug - ReadFile:./share.conf
Debug - ReadFile:./share.conf
Debug - ReadFile:./dev_certs/metadata/type_ibmshare_root_dev58.crt
Debug - WriteFile:/etc/swanctl/x509ca/type_ibmshare_root_dev58.crt
Debug - Folder created:/etc/swanctl/x509ca
Debug - ReadFile:./dev_certs/metadata/type_ibmshare_root_dal_preprod.crt
Debug - WriteFile:/etc/swanctl/x509ca/type_ibmshare_root_dal_preprod.crt
Debug - ReadFile:./dev_certs/metadata/type_ibmshare_root_wdc_preprod.crt
Debug - WriteFile:/etc/swanctl/x509ca/type_ibmshare_root_wdc_preprod.crt
Debug - ReadFile:./dev_certs/metadata/type_ibmshare_root_dev83.crt
Debug - WriteFile:/etc/swanctl/x509ca/type_ibmshare_root_dev83.crt
Debug - ReadFile:./dev_certs/metadata/type_ibmshare_root_7282.crt
Debug - WriteFile:/etc/swanctl/x509ca/type_ibmshare_root_7282.crt
Debug - ReadFile:./dev_certs/metadata/type_ibmshare_root_dev13.crt
Debug - WriteFile:/etc/swanctl/x509ca/type_ibmshare_root_dev13.crt
Debug - ReadFile:./dev_certs/metadata/type_ibmshare_root_dev93.crt
Debug - WriteFile:/etc/swanctl/x509ca/type_ibmshare_root_dev93.crt
Debug - Folder created:/etc/ibmcloud
Debug - RunCmd: ReloadCerts (/usr/sbin/swanctl --load-creds)
Installing certs for: metadata
Info  - IpSec using StrongSwan(5.8.2)
Debug - RunCmd: ListNfsMounts (mount -t nfs,nfs4)
Debug - Existing nfs/nfs4 mounts found:0
Debug - StrongSwan cleanup config files Total(0) Mounted(0) Deleted(0) Recent(0)
Debug - RunCmd: /usr/sbin/swanctl --list-conns
Debug - ReadFile:./share.conf
Debug - ReadFile:./share.conf
Debug - Cleanup folder:/etc/swanctl/x509ca
Debug - ReadFile:./certs/metadata/type_ibmshare_root_par.crt
Debug - WriteFile:/etc/swanctl/x509ca/type_ibmshare_root_par.crt
Debug - Folder created:/etc/swanctl/x509ca
Debug - ReadFile:./certs/metadata/type_ibmshare_root_sao.crt
Debug - WriteFile:/etc/swanctl/x509ca/type_ibmshare_root_sao.crt
Debug - ReadFile:./certs/metadata/type_ibmshare_root_dal.crt
Debug - WriteFile:/etc/swanctl/x509ca/type_ibmshare_root_dal.crt
Debug - ReadFile:./certs/metadata/type_ibmshare_root_osa.crt
Debug - WriteFile:/etc/swanctl/x509ca/type_ibmshare_root_osa.crt
Debug - ReadFile:./certs/metadata/type_ibmshare_root_tok.crt
Debug - WriteFile:/etc/swanctl/x509ca/type_ibmshare_root_tok.crt
Debug - ReadFile:./certs/metadata/type_ibmshare_root_tor.crt
Debug - WriteFile:/etc/swanctl/x509ca/type_ibmshare_root_tor.crt
Debug - ReadFile:./certs/metadata/type_ibmshare_root_mad.crt
Debug - WriteFile:/etc/swanctl/x509ca/type_ibmshare_root_mad.crt
Debug - ReadFile:./certs/metadata/type_ibmshare_root_syd.crt
Debug - WriteFile:/etc/swanctl/x509ca/type_ibmshare_root_syd.crt
Debug - ReadFile:./certs/metadata/type_ibmshare_root_wdc.crt
Debug - WriteFile:/etc/swanctl/x509ca/type_ibmshare_root_wdc.crt
Debug - ReadFile:./certs/metadata/type_ibmshare_root_fra.crt
Debug - WriteFile:/etc/swanctl/x509ca/type_ibmshare_root_fra.crt
Debug - ReadFile:./certs/metadata/type_ibmshare_root_lon.crt
Debu [...]

2024-04-01 21:18 UTC, anand-desai commented
Hi @saicharansunkara-ibm 
Please copy either prod certs or stage certs.
No need to copy both.
Thanks

2024-04-01 21:20 UTC, anand-desai requested changes
Please copy either prod certs or stage certs( depending on the request). Not both.

2024-04-04 03:41 UTC, saicharansunkara-ibm commented
Hi @prankulmahajan, I've made updates so that the code wouldn't install prod certs in case if stage is used as the input parameter and would only install pre-prod certs. Could you please retest to confirm that it is working good on your end.

2024-04-04 08:56 UTC, prankulmahajan commented
Verified with new changes, working as expected.

2024-04-05 01:52 UTC, arahamad approved these changes
lgtm

2024-04-05 11:24 UTC, DreamAmbitious approved these changes

2024-04-05 11:24 UTC, merged