Bundle mount helper dependencies into mount helper package
IBM/vpc-file-storage-mount-helper pull request #14
Opened 2024-05-03 03:30 UTC by saicharansunkara-ibm

Also added functionality to verify checksum for these downloaded dependent packages

2024-05-06 11:42 UTC, prankulmahajan requested changes

2024-05-06 11:42 UTC, prankulmahajan commented on mount-helper/install/packages/verify_chksum.sh
This file is duplicate and can be removed

2024-05-06 11:42 UTC, prankulmahajan commented on mount-helper/install/install.sh
>          yum install -y --nogpgcheck "https://dl.fedoraproject.org/pub/epel/epel-release-latest-$MAJOR_VERSION.noarch.rpm"
This can be removed as epel is there is packages folder

2024-05-06 11:42 UTC, prankulmahajan commented on mount-helper/install/install.sh
>              apt-get purge -y --auto-remove "${app%-*}"
Can we have a similar condition for .deb also to truncate the list of app name.

2024-05-06 12:25 UTC, prankulmahajan commented
Can you confirm if you too see this warning while trying to install?
```
warning: packages/rhel-strongswan_5.9.10-1.el8.rpm: Header V4 RSA/SHA256 Signature, key ID 2f86d6a1: NOKEY

```

2024-05-07 12:20 UTC, prankulmahajan commented
Hi @saicharansunkara-ibm I tested with these changes, it is not working in IKS Ubuntu 20.04. mount command is stuck.

```
root@pres-cot15ei10ad13q2spfh0-prankuliks-default-0000022e:/# mount -t ibmshare -o secure=true xxx test
Info  - IpSec using StrongSwan(5.8.2)
Debug - RunCmd: /usr/sbin/swanctl --list-conns
Debug - Config data unchanged:/etc/swanctl/conf.d/type_ibmshare_10.240.0.154.conf
Debug - StrongSwan cleanup config files Total(1) Mounted(0) Deleted(0) Recent(1)
Debug - RunCmd: ReloadConfig (/usr/sbin/swanctl --load-all)
Debug - File unlocked:/var/lock/ibm_mount_helper.lck
Debug - RunCmd: MountCmd (mount -t nfs4 -o sec=sys,nfsvers=4.1,rw 10.240.0.154:/098e71b8_6193_499a_9840_ec4f3c4c6933 /test)




```

2024-05-07 12:55 UTC, prankulmahajan commented
Also the Makefile expected chksum file to be present in install folder but is not present there

2024-05-09 11:07 UTC, prankulmahajan commented
Issues found:

1. Remove chksum.sh file from make clean target
```
root@prankul-vsi:~/go/src/github.com/sai/vpc-file-storage-mount-helper/mount-helper# make clean
rm -rf mount.ibmshare-0.0.3
rm -rf ./src/__pycache__
rm -rf ./test/__pycache__
rm -f ./install/*.rpm
rm -f ./install/*.deb
rm -rf ./install/certs
rm -rf ./install/dev_certs
mkdir ./install/certs
mkdir ./install/dev_certs
rm -f ./install/*_*.sh
rm -rf *.gz
root@prankul-vsi:~/go/src/github.com/sai/vpc-file-storage-mount-helper/mount-helper# make prod
=== Starting production build ===
# Prepare dependencies for offline installation
cp: cannot stat 'verify_chksum.sh': No such file or directory
make: *** [Makefile:141: prod] Error 
```

2024-05-09 11:09 UTC, prankulmahajan commented on mount-helper/install/install.sh
> +    install_apps packages/ubuntu-libstrongswan-standard-plugins_${LIBSTRONGSWAN_VERSION}.deb packages/ubuntu-libcharon-extauth-plugins_${LIBCHARON_EXTAUTH_PLUGINS_VERSION}.deb packages/ubuntu-libstro
`ubuntu-strongswan-libcharon` instead of `ubuntu-trongswan-libcharon`

2024-05-20 13:21 UTC, prankulmahajan requested changes

2024-05-20 13:21 UTC, prankulmahajan commented on mount-helper/Makefile
> +		wget -O ubuntu-libstrongswan-standard-plugins_$(LIBSTRONGSWAN_VERSION).deb "http://security.ubuntu.com/ubuntu/pool/main/s/strongswan/libstrongswan-standard-plugins_$(LIBSTRONGSWAN_VERSION)_amd64.de
This wont be required with new approach. Can you please update it?

2024-05-20 13:21 UTC, prankulmahajan commented on mount-helper/packages/rhel/8.8/epel-release-latest-8.noarch.rpm
We have two folders with same name "packages". Can we differentiate it in some form?

2024-05-20 13:21 UTC, prankulmahajan commented on mount-helper/install/packages/verifychksum.sh
There is duplicate file outisde packages folder. Can we keep only the relevant one?

2024-05-21 14:54 UTC, prankulmahajan commented
With new approach tested on IKS cluster,
```
❯ kubectl get pods -n kube-system -o wide| grep insta
installer-2p7nk                                       1/1     Running   0             11m   10.240.0.60     10.240.0.60   <none>           <none>
installer-fndq5                                       1/1     Running   0             11m   10.240.0.62     10.240.0.62   <none>           <none>

❯ kubectl logs installer-2p7nk -n kube-system -c installer -f
This is a Debian-based system
No (mount.ibmshare) package currently installed on the system
Installing latest version available...
Linux(Ubuntu) Version(20.04) distro
Linux version supported - Ubuntu (20.04)
Using install app: apt-get
Wait for cloud-init to complete.

status: done
extended_status: done
boot_status_code: enabled-by-generator
last_update: Mon, 20 May 2024 11:09:08 +0000
detail: DataSourceNoCloud [seed=/dev/vdb][dsmode=net]
errors: []
recoverable_errors: {}
Linux(Ubuntu) Version(20.04) distro
Linux version supported - Ubuntu (20.04)
Using install app: apt-get
Python 3.8.10 installed
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Package 'needrestart' is not installed, so not removed
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
Linux(Ubuntu) Version(20.04) distro
Linux version supported - Ubuntu (20.04)
Using install app: apt-get
Linux(Ubuntu) Version(20.04) distro
Linux version supported - Ubuntu (20.04)
Using install app: apt-get
Skipping package keyutils for uninstallation as it is pre-installed on the system
Linux(Ubuntu) Version(20.04) distro
Linux version supported - Ubuntu (20.04)
Using install app: apt-get
Linux(Ubuntu) Version(20.04) distro
Linux version supported - Ubuntu (20.04)
Using install app: apt-get
Installing package libstrongswan
Selecting previously unselected package libstrongswan-extra-plugins.
(Reading database ... 70588 files and directories currently installed.)
Preparing to unpack .../libstrongswan-extra-plugins_5.8.2-1ubuntu3.6_amd64.deb ...
Unpacking libstrongswan-extra-plugins (5.8.2-1ubuntu3.6) ...
Selecting previously unselected package libstrongswan-standard-plugins.
Preparing to unpack .../libstrongswan-standard-plugins_5.8.2-1ubuntu3.6_amd64.deb ...
Unpacking libstrongswan-standard-plugins (5.8.2-1ubuntu3.6) ...
Selecting previously unselected package libstrongswan.
Preparing to unpack .../libstrongswan_5.8.2-1ubuntu3.6_amd64.deb ...
Unpacking libstrongswan (5.8.2-1ubuntu3.6) ...
Setting up libstrongswan (5.8.2-1ubuntu3.6) ...

Configuration file '/etc/strongswan.conf', does not exist on system.
Installing new config file as you requested.

Configuration file '/etc/strongswan.d/charon/aes.conf', does not exist on system.
Installing new config file as you requested.

Configuration file '/etc/strongswan.d/charon/attr.conf', does not exist on system.
Installing new config file as you requested.

Configuration file '/etc/strongswan.d/charon/constraints.conf', does not exist on system.
Installing new config file as you requested.

Configuration file '/etc/strongswan.d/charon/dnskey.conf', does not exist on system.
Installing new config file as you requested.

Configuration file '/etc/strongswan.d/charon/drbg.conf', does not exist on system.
Installing new config file as you requested.

Configuration file '/etc/strongswan.d/charon/fips-prf.conf', does not exist on system.
Installing new config file as you requested.

Configuration file '/etc/strongswan.d/charon/gmp.conf', does not exist on system.
Installing new config file as you requested.

Configuration file '/etc/strongswan.d/charon/hmac.conf', does not exist on system.
Installing new config file as you requested.

Configuration file '/etc/strongswan.d/charon/kernel-netlink.conf', does not exist on system.
Installing new config file as you requested.

Configuration file '/etc/strongswan.d/charon/md5.conf', does not exist on system.
Installing new config file as you requested.

Configuration file '/etc/strongswan.d/charon/mgf1.conf', does not exist on system.
Installing new config file as you requested.

Configuration file '/etc/strongswan.d/charon/nonce.conf', does not exist on system.
Installing new config file as you requested.

Configuration file '/etc/strongswan.d/charon/pem.conf', does not exist on system.
Installing new config file as you requested.

Configuration file '/etc/strongswan.d/charon/pgp.conf', does not exist on system.
Installing new config file as you requested.

Configuration file '/etc/strongswan.d/charon/pkcs1.conf', does not exist on system.
Installing new config file as you requested.

Configuration file '/etc/strongswan.d/charon/pkcs12.conf', does not exist on system.
Installing new config file as you requested.

Configuration file '/etc/strongswan.d/charon/pkcs7.conf', does not exist on system.
Installing new config file as you requested.

Configuration file '/etc/strongswan.d/charon/pkcs8.conf', does not exist on system.
Installing new config file as you requested.

Configuration file '/etc/strongswan.d/charon/pubkey.conf', does not exist on system.
Installing new config file as you requested.

Configuration file '/etc/strongswan.d/charon/random.conf', does not exist on system.
Installing new config file as you requested.

Configuration file '/etc/strongswan.d/charon/rc2.conf', does not exist on system.
Installing new config file as you requested.

Configuration file '/etc/strongswan.d/charon/resolve.conf', does not exist on system.
Installing new config file as you requested.

Configuration file '/etc/strongswan.d/charon/revocation.conf', does not exist on system.
Installing new config file as you requested.

Configuration file '/etc/strongswan.d/charon/sha1.conf', does not exist on system.
Installing new config file as you requested.

Configuration file '/etc/strongswan.d/charon/sha2.conf', does not exist on system.
Installing new config file as you requested.

Configuration file '/etc/strongswan.d/charon/sshkey.conf', does not exist on system.
Installing new config file as you requested.

Configuration file '/etc/strongswan.d/charon/x509.conf', does not exist on system.
Installing new config file as you requested.

Configuration file '/etc/strongswan.d/charon/xcbc.conf', does not exist on system.
Installing new config file as you requested.
Setting up libstrongswan-extra-plugins (5.8.2-1ubuntu3.6) ...

Configuration file '/etc/strongswan.d/charon/af-alg.conf', does not exist on system.
Installing new config file as you requested.

Configuration file '/etc/strongswan.d/charon/ccm.conf', does not exist on system.
Installing new config file as you requested.

Configuration file '/etc/strongswan.d/charon/chapoly.conf', does not exist on system.
Installing new config file as you requested.

Configuration file '/etc/strongswan.d/charon/cmac.conf', does not exist on system.
Installing new config file as you requested.

Configuration file '/etc/strongswan.d/charon/ctr.conf', does not exist on system.
Installing new config file as you requested.

Configuration file '/etc/strongswan.d/charon/curl.conf', does not exist on system.
Installing new config file as you requested.

Configuration file '/etc/strongswan.d/charon/curve25519.conf', does not exist on system.
Installing new config file as you requested.

Configuration file '/etc/strongswan.d/charon/gcrypt.conf', does not exist on system.
Installing new config file as you requested.

Configuration file '/etc/strongswan.d/charon/ldap.conf', does not exist on system.
Installing new config file as you requested.

Configuration file '/etc/strongswan.d/charon/ntru.conf', does not exist on system.
Installing new config file as you requested.

Configuration file '/etc/strongswan.d/charon/pkcs11.conf', does not exist on system.
Installing new config file as you requested.

Configuration file '/etc/strongswan.d/charon/rdrand.conf', does not exist on system.
Installing new config file as you requested.

Configuration file '/etc/strongswan.d/charon/test-vectors.conf', does not exist  [...]

2024-05-22 13:13 UTC, prankulmahajan commented
@saicharansunkara-ibm checking ROKS use case (RHEL 8.9)
```
Installing package packages/epel-release-*.rpm
error: File not found by glob: packages/rhel/8.9/packages/epel-release-*.rpm*
```

2024-05-22 13:18 UTC, prankulmahajan commented on mount-helper/install/install.sh
> +        fi
Any reason why epel is installed seperately than other packages and not included in "package_list"?

Also the path might be causing installation issue,
`install_apps packages/rhel/$VERSION/epel-release-*.rpm`

2024-05-22 17:18 UTC, arahamad approved these changes
lgtm, please verify changes on IKS and ROKS

2024-05-23 07:51 UTC, prankulmahajan approved these changes
@arahamad @saicharansunkara-ibm 

- **IKS (Ubuntu 20.04)** : Verified installation, uninstallation, mounting + mounting (non-eit) volume
- **ROKS (RHEL 8.9)** : Verified installation, uninstallation. Mounting cant be tested as metadata service is not enabled. (Also as per discussion with Sai, he couldn't verify either on VSI as there is no 8.9 image available)

2024-05-24 13:34 UTC, anand-desai approved these changes

2024-05-28 01:26 UTC, saicharansunkara-ibm commented
Test verification:
**Ubuntu 20.04:**
`root@sai-charan-share-10:~# mount -t ibmshare -o secure=true 10.250.0.16:/f34e8559_0e1e_41ce_924d_21e3723090f0 /mnt/testshare/
Info  - IpSec using StrongSwan(5.8.2)
Debug - RunCmd: /usr/sbin/swanctl --list-conns
Debug - Config data unchanged:/etc/swanctl/conf.d/type_ibmshare_10.250.0.16.conf
Debug - StrongSwan cleanup config files Total(1) Mounted(0) Deleted(0) Recent(1)
Debug - RunCmd: ReloadConfig (/usr/sbin/swanctl --load-all)
Debug - File unlocked:/var/lock/ibm_mount_helper.lck
Debug - RunCmd: MountCmd (mount -t nfs4 -o sec=sys,nfsvers=4.1,rw 10.250.0.16:/f34e8559_0e1e_41ce_924d_21e3723090f0 /mnt/testshare)
Debug - RunCmd: LoadCert (openssl x509 -in /etc/swanctl/x509ca/type_ibmshare_int.crt -noout -dates -subject -issuer)
Debug - RunCmd: LoadCert (openssl x509 -in /etc/swanctl/x509ca/type_ibmshare_root_par.crt -noout -dates -subject -issuer)
Share successfully mounted:
root@sai-charan-share-10:~# lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 20.04.6 LTS
Release:	20.04
Codename:	focal`

**Ubuntu 22.04:**
`root@sai-charan-share-11:~# mount -t ibmshare -o secure=true 10.250.0.16:/f34e8559_0e1e_41ce_924d_21e3723090f0 /mnt/testshare/
Info  - IpSec using StrongSwan(5.9.5)
Debug - RunCmd: /usr/sbin/swanctl --list-conns
Debug - Config data unchanged:/etc/swanctl/conf.d/type_ibmshare_10.250.0.16.conf
Debug - StrongSwan cleanup config files Total(1) Mounted(0) Deleted(0) Recent(1)
Debug - RunCmd: ReloadConfig (/usr/sbin/swanctl --load-all)
Debug - File unlocked:/var/lock/ibm_mount_helper.lck
Debug - RunCmd: MountCmd (mount -t nfs4 -o sec=sys,nfsvers=4.1,rw 10.250.0.16:/f34e8559_0e1e_41ce_924d_21e3723090f0 /mnt/testshare)
Debug - RunCmd: LoadCert (openssl x509 -in /etc/swanctl/x509ca/type_ibmshare_int.crt -noout -dates -subject -issuer)
Debug - RunCmd: LoadCert (openssl x509 -in /etc/swanctl/x509ca/type_ibmshare_root_tor.crt -noout -dates -subject -issuer)
Share successfully mounted:
root@sai-charan-share-11:~# lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 22.04.4 LTS
Release:	22.04
Codename:	jammy`

Ubuntu 24.04:
`root@sai-charan-share-9:~/MHtest# mount -t ibmshare -o secure=true 10.250.0.16:/f34e8559_0e1e_41ce_924d_21e3723090f0 /mnt/testshare/
Info  - IpSec using StrongSwan(5.9.13)
Info  - Certificates updated successfully
Debug - Setting Timer: 2024-05-28 01:49:06 UTC
Debug - WriteFile:/etc/systemd/system/mount_helper.timer
Debug - WriteFile:/etc/systemd/system/mount_helper.service
Debug - RunCmd: /bin/systemctl enable mount_helper.timer
Debug - RunCmd: /bin/systemctl restart mount_helper.timer
Debug - RunCmd: LoadCert (openssl x509 -in /etc/swanctl/x509/type_ibmshare.pem -noout -dates -subject -issuer)
Debug - File unlocked:/var/lock/ibm_mount_helper_renew.lck
Debug - Certificate will be renewed at: 2024-05-28 01:49:06 UTC
Debug - RunCmd: /usr/sbin/swanctl --list-conns
Debug - WriteFile:/etc/swanctl/conf.d/type_ibmshare_10.250.0.16.conf
Debug - Config file created ok:/etc/swanctl/conf.d/type_ibmshare_10.250.0.16.conf
Debug - StrongSwan cleanup config files Total(1) Mounted(0) Deleted(0) Recent(1)
Debug - RunCmd: ReloadConfig (/usr/sbin/swanctl --load-all)
Debug - File unlocked:/var/lock/ibm_mount_helper.lck
Debug - RunCmd: MountCmd (mount -t nfs4 -o sec=sys,nfsvers=4.1,rw 10.250.0.16:/f34e8559_0e1e_41ce_924d_21e3723090f0 /mnt/testshare)
Debug - RunCmd: LoadCert (openssl x509 -in /etc/swanctl/x509ca/type_ibmshare_int.crt -noout -dates -subject -issuer)
Debug - RunCmd: LoadCert (openssl x509 -in /etc/swanctl/x509ca/type_ibmshare_root_tor.crt -noout -dates -subject -issuer)
Share successfully mounted:
root@sai-charan-share-9:~/MHtest#
root@sai-charan-share-9:~/MHtest#
root@sai-charan-share-9:~/MHtest# lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 24.04 LTS
Release:	24.04
Codename:	noble`

**RHEL 8.8:**
`[root@sai-charan-share-12 MHtest]# mount -t ibmshare -o secure=true 10.250.0.16:/f34e8559_0e1e_41ce_924d_21e3723090f0 /mnt/testshare/
Info  - IpSec using StrongSwan(5.9.10)
Info  - Certificates updated successfully
Debug - Setting Timer: 2024-05-28 02:07:38 UTC
Debug - WriteFile:/etc/systemd/system/mount_helper.timer
Debug - WriteFile:/etc/systemd/system/mount_helper.service
Debug - RunCmd: /bin/systemctl enable mount_helper.timer
Debug - RunCmd: /bin/systemctl restart mount_helper.timer
Debug - RunCmd: LoadCert (openssl x509 -in /etc/strongswan/swanctl/x509/type_ibmshare.pem -noout -dates -subject -issuer)
Debug - File unlocked:/var/lock/ibm_mount_helper_renew.lck
Debug - Certificate will be renewed at: 2024-05-28 02:07:38 UTC
Debug - RunCmd: /usr/sbin/swanctl --list-conns
Debug - WriteFile:/etc/strongswan/swanctl/conf.d/type_ibmshare_10.250.0.16.conf
Debug - Config file created ok:/etc/strongswan/swanctl/conf.d/type_ibmshare_10.250.0.16.conf
Debug - StrongSwan cleanup config files Total(1) Mounted(0) Deleted(0) Recent(1)
Debug - RunCmd: ReloadConfig (/usr/sbin/swanctl --load-all)
Debug - File unlocked:/var/lock/ibm_mount_helper.lck
Debug - RunCmd: MountCmd (mount -t nfs4 -o sec=sys,nfsvers=4.1,rw 10.250.0.16:/f34e8559_0e1e_41ce_924d_21e3723090f0 /mnt/testshare)
Debug - RunCmd: LoadCert (openssl x509 -in /etc/strongswan/swanctl/x509ca/type_ibmshare_int.crt -noout -dates -subject -issuer)
Debug - RunCmd: LoadCert (openssl x509 -in /etc/strongswan/swanctl/x509ca/type_ibmshare_root_dal.crt -noout -dates -subject -issuer)
Share successfully mounted:
[root@sai-charan-share-12 MHtest]# cat /etc/os-release
NAME="Red Hat Enterprise Linux"
VERSION="8.8 (Ootpa)"
ID="rhel"
ID_LIKE="fedora"
VERSION_ID="8.8"
PLATFORM_ID="platform:el8"
PRETTY_NAME="Red Hat Enterprise Linux 8.8 (Ootpa)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:redhat:enterprise_linux:8::baseos"
HOME_URL="https://www.redhat.com/"
DOCUMENTATION_URL="https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/8"
BUG_REPORT_URL="https://bugzilla.redhat.com/"

REDHAT_BUGZILLA_PRODUCT="Red Hat Enterprise Linux 8"
REDHAT_BUGZILLA_PRODUCT_VERSION=8.8
REDHAT_SUPPORT_PRODUCT="Red Hat Enterprise Linux"
REDHAT_SUPPORT_PRODUCT_VERSION="8.8"
[root@sai-charan-share-12 MHtest]#`

2024-05-28 08:33 UTC, DreamAmbitious approved these changes

2024-05-28 08:33 UTC, merged