Add update option to mount helper
IBM/vpc-file-storage-mount-helper pull request #23
Opened 2024-08-07 18:45 UTC by riddhi-ibm

2024-08-07 18:45 UTC, riddhi-ibm commented
```
root@riddhi-test-vsi-ugrade-package:~# ./install.sh update
Linux(Ubuntu) Version(22.04) distro
Linux version supported - Ubuntu (22.04)
Using install app: apt-get
Wait for cloud-init to complete.

status: done
extended_status: done
boot_status_code: enabled-by-generator
last_update: Wed, 07 Aug 2024 17:10:32 +0000
detail: DataSourceNoCloud [seed=/dev/vdb][dsmode=net]
errors: []
recoverable_errors: {}
Linux(Ubuntu) Version(22.04) distro
Linux version supported - Ubuntu (22.04)
Using install app: apt-get
Python 3.10.12 installed
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
Package 'needrestart' is not installed, so not removed
The following packages were automatically installed and are no longer required:
  libintl-perl libintl-xs-perl libmodule-find-perl libmodule-scandeps-perl libproc-processtable-perl libsort-naturally-perl libterm-readkey-perl
Use 'apt autoremove' to remove them.
0 upgraded, 0 newly installed, 0 to remove and 7 not upgraded.
Linux(Ubuntu) Version(22.04) distro
Linux version supported - Ubuntu (22.04)
Using install app: apt-get
Linux(Ubuntu) Version(22.04) distro
Linux version supported - Ubuntu (22.04)
Using install app: apt-get
Installing package mount.ibmshare-0.0.4.deb
(Reading database ... 106267 files and directories currently installed.)
Preparing to unpack mount.ibmshare-0.0.4.deb ...
Unpacking mount.ibmshare-0.0.4 (0.0.4) over (0.0.4) ...
Setting up mount.ibmshare-0.0.4 (0.0.4) ...
Installing certs for: metadata
Info  - IpSec using StrongSwan(5.9.5)
Debug - RunCmd: ListNfsMounts (mount -t nfs,nfs4)
Debug - Existing nfs/nfs4 mounts found:0
Debug - StrongSwan cleanup config files Total(0) Mounted(0) Deleted(0) Recent(0)
Debug - RunCmd: /usr/sbin/swanctl --list-conns
Debug - ReadFile:./share.conf
Debug - ReadFile:./share.conf
Debug - Cleanup folder:/etc/swanctl/x509ca
Debug - ReadFile:./certs/metadata/type_ibmshare_root_dal_preprod.crt
Debug - WriteFile:/etc/swanctl/x509ca/type_ibmshare_root_dal_preprod.crt
Debug - Folder created:/etc/swanctl/x509ca
Debug - ReadFile:./certs/metadata/type_ibmshare_root_syd.crt
Debug - WriteFile:/etc/swanctl/x509ca/type_ibmshare_root_syd.crt
Debug - ReadFile:./certs/metadata/type_ibmshare_root_wdc_preprod.crt
Debug - WriteFile:/etc/swanctl/x509ca/type_ibmshare_root_wdc_preprod.crt
Debug - ReadFile:./certs/metadata/type_ibmshare_root_mad.crt
Debug - WriteFile:/etc/swanctl/x509ca/type_ibmshare_root_mad.crt
Debug - ReadFile:./certs/metadata/type_ibmshare_root_dev93.crt
Debug - WriteFile:/etc/swanctl/x509ca/type_ibmshare_root_dev93.crt
Debug - ReadFile:./certs/metadata/type_ibmshare_root_dev92.crt
Debug - WriteFile:/etc/swanctl/x509ca/type_ibmshare_root_dev92.crt
Debug - ReadFile:./certs/metadata/type_ibmshare_root_dev83.crt
Debug - WriteFile:/etc/swanctl/x509ca/type_ibmshare_root_dev83.crt
Debug - ReadFile:./certs/metadata/type_ibmshare_root_lon.crt
Debug - WriteFile:/etc/swanctl/x509ca/type_ibmshare_root_lon.crt
Debug - ReadFile:./certs/metadata/type_ibmshare_root_osa.crt
Debug - WriteFile:/etc/swanctl/x509ca/type_ibmshare_root_osa.crt
Debug - ReadFile:./certs/metadata/type_ibmshare_root_tor.crt
Debug - WriteFile:/etc/swanctl/x509ca/type_ibmshare_root_tor.crt
Debug - ReadFile:./certs/metadata/type_ibmshare_root_dev58.crt
Debug - WriteFile:/etc/swanctl/x509ca/type_ibmshare_root_dev58.crt
Debug - ReadFile:./certs/metadata/type_ibmshare_root_sao.crt
Debug - WriteFile:/etc/swanctl/x509ca/type_ibmshare_root_sao.crt
Debug - ReadFile:./certs/metadata/type_ibmshare_root_wdc.crt
Debug - WriteFile:/etc/swanctl/x509ca/type_ibmshare_root_wdc.crt
Debug - ReadFile:./certs/metadata/type_ibmshare_root_fra.crt
Debug - WriteFile:/etc/swanctl/x509ca/type_ibmshare_root_fra.crt
Debug - ReadFile:./certs/metadata/type_ibmshare_root_dal.crt
Debug - WriteFile:/etc/swanctl/x509ca/type_ibmshare_root_dal.crt
Debug - ReadFile:./certs/metadata/type_ibmshare_root_tok.crt
Debug - WriteFile:/etc/swanctl/x509ca/type_ibmshare_root_tok.crt
Debug - ReadFile:./certs/metadata/type_ibmshare_root_dev13.crt
Debug - WriteFile:/etc/swanctl/x509ca/type_ibmshare_root_dev13.crt
Debug - ReadFile:./certs/metadata/type_ibmshare_root_par.crt
Debug - WriteFile:/etc/swanctl/x509ca/type_ibmshare_root_par.crt
Debug - ReadFile:./certs/metadata/type_ibmshare_root_7282.crt
Debug - WriteFile:/etc/swanctl/x509ca/type_ibmshare_root_7282.crt
Debug - RunCmd: ReloadCerts (/usr/sbin/swanctl --load-creds)

IBM Mount Share Helper: Install completed ok
```

2024-08-07 20:43 UTC, anand-desai approved these changes

2024-08-07 20:44 UTC, saicharansunkara-ibm approved these changes

2024-08-08 07:49 UTC, prankulmahajan commented
Suggestion for simplicity purposes, there are mutiple options now which can be passed to this install.sh
```
./install.sh UNINSTALL
./install.sh stage 
./install.sh update
```

It is getting confusing just to pass the simple argument, why not pass the flag instead, like
```
./install.sh --uninstall
./install.sh --env stage
./install.sh --update
```

Maybe later but this way it will be easier for user to understand and inline with how other scripts are also called.

2024-08-08 07:49 UTC, prankulmahajan commented
@riddhi-ibm Also in the PR description can you give the scenarios which are handled via this PR? Thanks

2024-08-08 13:25 UTC, riddhi-ibm commented
> Suggestion for simplicity purposes, there are mutiple options now which can be passed to this install.sh
> 
> ```
> ./install.sh UNINSTALL
> ./install.sh stage 
> ./install.sh update
> ```
> 
> It is getting confusing just to pass the simple argument, why not pass the flag instead, like
> 
> ```
> ./install.sh --uninstall
> ./install.sh --env stage
> ./install.sh --update
> ```
> 
> Maybe later but this way it will be easier for user to understand and inline with how other scripts are also called.

noted

2024-08-08 20:34 UTC, riddhi-ibm commented
I have updated options to 
./install.sh --uninstall
./install.sh stage
./install.sh --update

2024-08-11 18:49 UTC, prankulmahajan commented
@riddhi-ibm What is the expected command to be run in case of stage env? From what is checked

1. `# ./install.sh stage --update` -> Able to load stage certs
```
...
...
Installing certs for stage environment...
Info  - IpSec using StrongSwan(5.9.13)
Debug - RunCmd: ListNfsMounts (mount -t nfs,nfs4)
Debug - Existing nfs/nfs4 mounts found:0
Debug - StrongSwan cleanup config files Total(0) Mounted(0) Deleted(0) Recent(0)
Debug - RunCmd: /usr/sbin/swanctl --list-conns
Debug - ReadFile:./share.conf
Debug - ReadFile:./share.conf
Debug - Cleanup folder:/etc/swanctl/x509ca
Debug - ReadFile:./dev_certs/metadata/type_ibmshare_root_dev93.crt
Debug - WriteFile:/etc/swanctl/x509ca/type_ibmshare_root_dev93.crt
Debug - Folder created:/etc/swanctl/x509ca
Debug - ReadFile:./dev_certs/metadata/type_ibmshare_root_dev92.crt
Debug - WriteFile:/etc/swanctl/x509ca/type_ibmshare_root_dev92.crt
Debug - ReadFile:./dev_certs/metadata/type_ibmshare_root_7282.crt
Debug - WriteFile:/etc/swanctl/x509ca/type_ibmshare_root_7282.crt
Debug - ReadFile:./dev_certs/metadata/type_ibmshare_root_dev58.crt
Debug - WriteFile:/etc/swanctl/x509ca/type_ibmshare_root_dev58.crt
Debug - ReadFile:./dev_certs/metadata/type_ibmshare_root_dev13.crt
Debug - WriteFile:/etc/swanctl/x509ca/type_ibmshare_root_dev13.crt
Debug - ReadFile:./dev_certs/metadata/type_ibmshare_root_wdc_preprod.crt
Debug - WriteFile:/etc/swanctl/x509ca/type_ibmshare_root_wdc_preprod.crt
Debug - ReadFile:./dev_certs/metadata/type_ibmshare_root_dal_preprod.crt
Debug - WriteFile:/etc/swanctl/x509ca/type_ibmshare_root_dal_preprod.crt
Debug - ReadFile:./dev_certs/metadata/type_ibmshare_root_dev83.crt
Debug - WriteFile:/etc/swanctl/x509ca/type_ibmshare_root_dev83.crt
Debug - RunCmd: ReloadCerts (/usr/sbin/swanctl --load-creds)

IBM Mount Share Helper: Install completed ok.
```

2. `# ./install.sh  --update stage` -> Install prod certs
```
...
...
Installing certs for: metadata
Info  - IpSec using StrongSwan(5.9.13)
Debug - RunCmd: ListNfsMounts (mount -t nfs,nfs4)
Debug - Existing nfs/nfs4 mounts found:0
Debug - StrongSwan cleanup config files Total(0) Mounted(0) Deleted(0) Recent(0)
Debug - RunCmd: /usr/sbin/swanctl --list-conns
Debug - ReadFile:./share.conf
Debug - ReadFile:./share.conf
Debug - Cleanup folder:/etc/swanctl/x509ca
Debug - ReadFile:./certs/metadata/type_ibmshare_root_syd.crt
Debug - WriteFile:/etc/swanctl/x509ca/type_ibmshare_root_syd.crt
Debug - Folder created:/etc/swanctl/x509ca
Debug - ReadFile:./certs/metadata/type_ibmshare_root_sao.crt
Debug - WriteFile:/etc/swanctl/x509ca/type_ibmshare_root_sao.crt
Debug - ReadFile:./certs/metadata/type_ibmshare_root_osa.crt
Debug - WriteFile:/etc/swanctl/x509ca/type_ibmshare_root_osa.crt
Debug - ReadFile:./certs/metadata/type_ibmshare_root_dal.crt
Debug - WriteFile:/etc/swanctl/x509ca/type_ibmshare_root_dal.crt
Debug - ReadFile:./certs/metadata/type_ibmshare_root_wdc.crt
Debug - WriteFile:/etc/swanctl/x509ca/type_ibmshare_root_wdc.crt
Debug - ReadFile:./certs/metadata/type_ibmshare_root_lon.crt
Debug - WriteFile:/etc/swanctl/x509ca/type_ibmshare_root_lon.crt
Debug - ReadFile:./certs/metadata/type_ibmshare_root_fra.crt
Debug - WriteFile:/etc/swanctl/x509ca/type_ibmshare_root_fra.crt
Debug - ReadFile:./certs/metadata/type_ibmshare_root_tor.crt
Debug - WriteFile:/etc/swanctl/x509ca/type_ibmshare_root_tor.crt
Debug - ReadFile:./certs/metadata/type_ibmshare_root_par.crt
Debug - WriteFile:/etc/swanctl/x509ca/type_ibmshare_root_par.crt
Debug - ReadFile:./certs/metadata/type_ibmshare_root_mad.crt
Debug - WriteFile:/etc/swanctl/x509ca/type_ibmshare_root_mad.crt
Debug - ReadFile:./certs/metadata/type_ibmshare_root_tok.crt
Debug - WriteFile:/etc/swanctl/x509ca/type_ibmshare_root_tok.crt
Debug - RunCmd: ReloadCerts (/usr/sbin/swanctl --load-creds)
```

2024-08-12 08:59 UTC, prankulmahajan commented
@riddhi-ibm As per my testing there is a some problem with how the packages are handled for uninstallation, the packages are not getting deleted from system if we do `./uninstall.sh`
```
Reading package lists... Done
Building dependency tree       
Reading state information... Done
The following packages will be REMOVED:
  mount-helper-container-0.0.4*
0 upgraded, 0 newly installed, 1 to remove and 21 not upgraded.
After this operation, 0 B of additional disk space will be used.
(Reading database ... 70886 files and directories currently installed.)
Removing mount-helper-container-0.0.4 (0.0.4) ...
Removed /etc/systemd/system/multi-user.target.wants/mount-helper-container.service.
dpkg: warning: while removing mount-helper-container-0.0.4, directory '/usr/local/bin' not empty so not removed
Uninstalling (mount.ibmshare-0.0.5)...
Linux(Ubuntu) Version(20.04) distro
Linux version supported - Ubuntu (20.04)
Using install app: apt-get
Wait for cloud-init to complete.

status: done
extended_status: done
boot_status_code: enabled-by-generator
last_update: Fri, 09 Aug 2024 05:09:47 +0000
detail: DataSourceNoCloud [seed=/dev/vdb][dsmode=net]
errors: []
recoverable_errors: {}
Linux(Ubuntu) Version(20.04) distro
Linux version supported - Ubuntu (20.04)
Using install app: apt-get
Python 3.8.10 installed
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Package 'needrestart' is not installed, so not removed
0 upgraded, 0 newly installed, 0 to remove and 21 not upgraded.
Info  - IpSec using StrongSwan(5.8.2)
Debug - TearDown starting
Debug - Cleanup folder:/etc/swanctl/x509ca
Debug - Cleanup folder:/etc/swanctl/private
Debug - Cleanup folder:/etc/swanctl/x509
Debug - Cleanup folder:/etc/swanctl/conf.d
Debug - RunCmd: /bin/systemctl stop mount_helper.timer
Debug - RunCmd: /bin/systemctl disable mount_helper.timer
Debug - TearDown complete
Removing package mount.ibmshare-0.0.5.deb
Linux(Ubuntu) Version(20.04) distro
Linux version supported - Ubuntu (20.04)
Using install app: apt-get
Skipping package mount.ibmshare for uninstallation as it was pre-installed on the system
Removing package nfs-common
Linux(Ubuntu) Version(20.04) distro
Linux version supported - Ubuntu (20.04)
Using install app: apt-get
Skipping package nfs-common for uninstallation as it was pre-installed on the system
Removing package libnfsidmap2
Linux(Ubuntu) Version(20.04) distro
Linux version supported - Ubuntu (20.04)
Using install app: apt-get
Skipping package libnfsidmap2 for uninstallation as it was pre-installed on the system
Removing package rpcbind
Linux(Ubuntu) Version(20.04) distro
Linux version supported - Ubuntu (20.04)
Using install app: apt-get
Skipping package rpcbind for uninstallation as it was pre-installed on the system
Removing package libtirpc3
Linux(Ubuntu) Version(20.04) distro
Linux version supported - Ubuntu (20.04)
Using install app: apt-get
Skipping package libtirpc3 for uninstallation as it was pre-installed on the system
Removing package libtirpc-common
Linux(Ubuntu) Version(20.04) distro
Linux version supported - Ubuntu (20.04)
Using install app: apt-get
Skipping package libtirpc-common for uninstallation as it was pre-installed on the system
Removing package watchdog
Linux(Ubuntu) Version(20.04) distro
Linux version supported - Ubuntu (20.04)
Using install app: apt-get
Skipping package watchdog for uninstallation as it was pre-installed on the system
Removing package strongswan
Linux(Ubuntu) Version(20.04) distro
Linux version supported - Ubuntu (20.04)
Using install app: apt-get
Skipping package strongswan for uninstallation as it was pre-installed on the system
Removing package strongswan-starter
Linux(Ubuntu) Version(20.04) distro
Linux version supported - Ubuntu (20.04)
Using install app: apt-get
Skipping package strongswan-starter for uninstallation as it was pre-installed on the system
Removing package strongswan-charon
Linux(Ubuntu) Version(20.04) distro
Linux version supported - Ubuntu (20.04)
Using install app: apt-get
Skipping package strongswan-charon for uninstallation as it was pre-installed on the system
Removing package charon-systemd
Linux(Ubuntu) Version(20.04) distro
Linux version supported - Ubuntu (20.04)
Using install app: apt-get
Skipping package charon-systemd for uninstallation as it was pre-installed on the system
Removing package strongswan-libcharon
Linux(Ubuntu) Version(20.04) distro
Linux version supported - Ubuntu (20.04)
Using install app: apt-get
Skipping package strongswan-libcharon for uninstallation as it was pre-installed on the system
Removing package strongswan-swanctl
Linux(Ubuntu) Version(20.04) distro
Linux version supported - Ubuntu (20.04)
Using install app: apt-get
Skipping package strongswan-swanctl for uninstallation as it was pre-installed on the system
Removing package libcharon-extauth-plugins
Linux(Ubuntu) Version(20.04) distro
Linux version supported - Ubuntu (20.04)
Using install app: apt-get
Skipping package libcharon-extauth-plugins for uninstallation as it was pre-installed on the system
Removing package libcharon-extra-plugins
Linux(Ubuntu) Version(20.04) distro
Linux version supported - Ubuntu (20.04)
Using install app: apt-get
Skipping package libcharon-extra-plugins for uninstallation as it was pre-installed on the system
Removing package libstrongswan-extra-plugins
Linux(Ubuntu) Version(20.04) distro
Linux version supported - Ubuntu (20.04)
Using install app: apt-get
Skipping package libstrongswan-extra-plugins for uninstallation as it was pre-installed on the system
Removing package libstrongswan-standard-plugins
Linux(Ubuntu) Version(20.04) distro
Linux version supported - Ubuntu (20.04)
Using install app: apt-get
Skipping package libstrongswan-standard-plugins for uninstallation as it was pre-installed on the system
Removing package libstrongswan
Linux(Ubuntu) Version(20.04) distro
Linux version supported - Ubuntu (20.04)
Using install app: apt-get
Skipping package libstrongswan for uninstallation as it was pre-installed on the system
Removing package keyutils
Linux(Ubuntu) Version(20.04) distro
Linux version supported - Ubuntu (20.04)
Using install app: apt-get
Skipping package keyutils for uninstallation as it was pre-installed on the system

IBM Mount Share Helper: UnInstall completed ok.
```

From the logs it looks like `/etc/pre_installed_packages.txt` is being updated in case of --update which leads to skip uninstallation of all package ultimately. That needs to be fixed

2024-08-12 09:06 UTC, prankulmahajan requested changes

2024-08-12 09:06 UTC, prankulmahajan commented on mount-helper/install/install.sh
> +    if is_linux LINUX_UBUNTU && ([[ ! "$INSTALL_ARG" = "--update" ]]); then
This syntax needs to be fixed

2024-08-12 09:06 UTC, prankulmahajan commented on mount-helper/install/install.sh
> +    elif is_linux LINUX_RED_HAT && ([[ ! "$INSTALL_ARG" = "--update" ]]); then
same here

2024-08-12 09:06 UTC, prankulmahajan commented on mount-helper/install/install.sh
> +    if is_linux LINUX_UBUNTU && ([[ ! "$INSTALL_ARG" = "--update" ]]); then
Even in case install_arg is `--update`, the pre_installed_list is getting updated leeding to issues in uninstall

2024-08-12 12:24 UTC, riddhi-ibm commented on mount-helper/install/install.sh
> +    if [ "$INSTALL_ARG" == "stage" || "$INSTALL_ARG" == "--update-stage" ]; then
oops, I missed updating it in my PR, 
Thanks for the catch!

2024-08-12 13:35 UTC, prankulmahajan commented
Thanks @riddhi-ibm for the quick changes, I tested on IKS/ROKS cluster, the cases looks good. Am attaching the results below.

## IKS 1.30

#### Existing EIT users (fileShare created and mounted with data written to target path)

- [x] Cluster setup
```
prankul1            cqmcfnk20jenrqen2020   normal   1 week ago   2         Dallas     1.30.3_1531              Default               vpc-gen2

❯ kubectl get nodes
NAME          STATUS   ROLES    AGE     VERSION
10.240.0.48   Ready    <none>   8m      v1.30.3+IKS
10.240.0.49   Ready    <none>   7m57s   v1.30.3+IKS

# Enable operator and file
❯ ibmcloud ks cluster addon ls -c prankul1
OK
Name                   Version   Health State   Health Status
ibm-storage-operator   1.0       normal         Addon Ready. For more info: http://ibm.biz/addon-state (H1500)
vpc-block-csi-driver   5.1       normal         Addon Ready. For more info: http://ibm.biz/addon-state (H1500)
vpc-file-csi-driver    2.0       normal         Addon Ready. For more info: http://ibm.biz/addon-state (H1500)

# Enable EIT using addon cm (uses image icr.io/ibm/armada-vpc-package-deployer:v1.0.0-beta, mount.ibmshare 0.0.4 and mount-helper-container 0.0.3)

# Create PVC and mount it for app
❯ kubectl get pvc
NAME      STATUS   VOLUME                                     CAPACITY   ACCESS MODES   STORAGECLASS        VOLUMEATTRIBUTESCLASS   AGE
pvc-eit   Bound    pvc-da8fd10c-0b1d-4fa9-8d2e-0d3f86fe1c91   10Gi       RWX            ibmc-vpc-file-eit   <unset>                 97s

❯ kubectl get pods -owide
NAME                      READY   STATUS    RESTARTS   AGE   IP            NODE          NOMINATED NODE   READINESS GATES
eit-app-cd5c4f4dd-qxhbt   1/1     Running   0          14s   172.17.8.74   10.240.0.51   <none>           <none>
eit-app-cd5c4f4dd-xlfxk   1/1     Running   0          14s   172.17.8.75   10.240.0.51   <none>           <none>

❯ .
bash-5.1# df -h
Filesystem                Size      Used Available Use% Mounted on
overlay                  97.3G      5.2G     87.9G   6% /
tmpfs                    64.0M         0     64.0M   0% /dev
tmpfs                     7.7G         0      7.7G   0% /sys/fs/cgroup
10.240.0.47:/bb893252_482c_4d63_9883_b4d9c3adae1e
                         10.0G    320.0K     10.0G   0% /mount-path-eit
/dev/vda2                97.3G      5.2G     87.9G   6% /etc/hosts
/dev/vda2                97.3G      5.2G     87.9G   6% /dev/termination-log
/dev/vda2                97.3G      5.2G     87.9G   6% /etc/hostname
/dev/vda2                97.3G      5.2G     87.9G   6% /etc/resolv.conf
shm                      64.0M         0     64.0M   0% /dev/shm
tmpfs                    12.8G     16.0K     12.8G   0% /run/secrets/kubernetes.io/serviceaccount
tmpfs                     7.7G         0      7.7G   0% /proc/acpi
tmpfs                    64.0M         0     64.0M   0% /proc/kcore
tmpfs                    64.0M         0     64.0M   0% /proc/keys
tmpfs                    64.0M         0     64.0M   0% /proc/timer_list
tmpfs                    64.0M         0     64.0M   0% /proc/sched_debug
tmpfs                     7.7G         0      7.7G   0% /proc/scsi
tmpfs                     7.7G         0      7.7G   0% /sys/firmware
bash-5.1# cd mount-path-eit/
bash-5.1# ls
test.txt   test2.txt

# ssh indo node and confirm mh version
❯ runon 10.240.0.49 command bash
E0812 14:21:57.152857   59363 websocket.go:296] Unknown stream id 1, discarding message
                                                                                       groups: cannot find name for group ID 11
To run a command as administrator (user "root"), use "sudo <command>".
See "man sudo_root" for details.

root@test-cqmcfnk20jenrqen2020-prankul1-default-00000422:/# 
root@test-cqmcfnk20jenrqen2020-prankul1-default-00000422:/# 
root@test-cqmcfnk20jenrqen2020-prankul1-default-00000422:/# apt list --installed | grep mount.ibmshare

WARNING: apt does not have a stable CLI interface. Use with caution in scripts.

mount.ibmshare-0.0.4/now 0.0.4 all [installed,local]
root@test-cqmcfnk20jenrqen2020-prankul1-default-00000422:/# 
root@test-cqmcfnk20jenrqen2020-prankul1-default-00000422:/# apt list --installed | grep mount-helper

WARNING: apt does not have a stable CLI interface. Use with caution in scripts.

mount-helper-container-0.0.3/now 0.0.3 all [installed,local]
root@test-cqmcfnk20jenrqen2020-prankul1-default-00000422:/# 
root@test-cqmcfnk20jenrqen2020-prankul1-default-00000422:/# apt list --installed | grep strongswan

WARNING: apt does not have a stable CLI interface. Use with caution in scripts.

libstrongswan-extra-plugins/focal-updates,focal-security,now 5.8.2-1ubuntu3.6 amd64 [installed]
libstrongswan-standard-plugins/focal-updates,focal-security,now 5.8.2-1ubuntu3.6 amd64 [installed]
libstrongswan/focal-updates,focal-security,now 5.8.2-1ubuntu3.6 amd64 [installed]
strongswan-charon/focal-updates,focal-security,now 5.8.2-1ubuntu3.6 amd64 [installed]
strongswan-libcharon/focal-updates,focal-security,now 5.8.2-1ubuntu3.6 amd64 [installed]
strongswan-starter/focal-updates,focal-security,now 5.8.2-1ubuntu3.6 amd64 [installed]
strongswan-swanctl/focal-updates,focal-security,now 5.8.2-1ubuntu3.6 amd64 [installed]
strongswan/focal-updates,focal-security,now 5.8.2-1ubuntu3.6 all [installed]
root@test-cqmcfnk20jenrqen2020-prankul1-default-00000422:/# 
```
- [x]  Run installer job with updated deployer image -- Should pass (confirm logs)
```
❯ kubectl apply -f ds.yaml
daemonset.apps/installer created

❯ kubectl get pods -n kube-system -o wide -w| grep insta
installer-26kp6                                       1/1     Running   0              83s    10.240.0.50     10.240.0.50   <none>           <none>
installer-xdx8f                                       1/1     Running   0              83s    10.240.0.51     10.240.0.51   <none>           <none>

❯ kubectl logs installer-xdx8f -c installer -n kube-system -f
This is a Debian-based system
Newer version (0.0.5) of (mount.ibmshare) found. Updating...
Linux(Ubuntu) Version(20.04) distro
Linux version supported - Ubuntu (20.04)
Using install app: apt-get
Wait for cloud-init to complete.

status: done
extended_status: done
boot_status_code: enabled-by-generator
last_update: Mon, 12 Aug 2024 10:08:36 +0000
detail: DataSourceNoCloud [seed=/dev/vdb][dsmode=net]
errors: []
recoverable_errors: {}
Linux(Ubuntu) Version(20.04) distro
Linux version supported - Ubuntu (20.04)
Using install app: apt-get
Python 3.8.10 installed
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Package 'needrestart' is not installed, so not removed
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
Linux(Ubuntu) Version(20.04) distro
Linux version supported - Ubuntu (20.04)
Using install app: apt-get
Linux(Ubuntu) Version(20.04) distro
Linux version supported - Ubuntu (20.04)
Using install app: apt-get
Installing package mount.ibmshare-0.0.5.deb
Selecting previously unselected package mount.ibmshare-0.0.5.
(Reading database ... 70887 files and directories currently installed.)
Preparing to unpack mount.ibmshare-0.0.5.deb ...
Unpacking mount.ibmshare-0.0.5 (0.0.5) ...
dpkg: warning: overriding problem because --force enabled:
dpkg: warning: trying to overwrite '/sbin/mount.ibmshare', which is also in package mount.ibmshare-0.0.4 0.0.4
Setting up mount.ibmshare-0.0.5 (0.0.5) ...
Installing certs for stage environment...
Info  - IpSec using StrongSwan(5.8.2)
Debug - RunCmd: ListNfsMounts (mount -t nfs,nfs4)
Debug - Existing nfs/nfs4 mounts found:6
Debug - StrongSwan cleanup config files Total(1) Mounted(1) Deleted(0) Recent(0)
Debug - RunCmd: /usr/sbin/swanctl --list-conns
Debug - ReadFile:./share.conf
Debug - ReadFile:./share.conf
Debug - Cleanup folder:/etc/swanctl/x509ca
Debug - ReadFile:./dev_certs/metadata/type_ibmshare_root_dev13.crt
Debug - WriteFile:/etc/swanctl/x509ca/type_ibmshare_root_dev13.crt
Debug - Folder created:/etc/swanctl/x509ca
Debug - ReadFile:./dev_certs/meta [...]

2024-08-12 14:15 UTC, merged